const buildingInfo = [
    {
        key: 1,
        id: "culc",
        title: "Clough Undergraduate Learning Commons",
        desc: "The building serves as an interdisciplinary facility to encourage collaboration and technologically enhanced teaching and learning. The Clough Commons, which was built with LEED certification in mind, contains various sustainability features and a roof garden, demonstrating Georgia Tech's commitment to sustainable design. In August 2012, the building, staged as a building within Googleplex, was a major piece of the set of the 2013 film The Internship.",
        microwave: "This building has a microwave in Room 284: Second floor CULC, requires Buzzcard access (possibly faculty only), locked after hours",
        buzzcard: "Requires buzzcard access after 6pm",
        vending: "Has a vending machine on every floor",
        imgurl: "https://http.cat/202",
    },
    {
        key: 2,
        id: "techgreen",
        title: "Tech Green",
        desc: "Tech Green is the great lawn of Georgia Tech and the gathering spot for 1000 attendees and hosts graduation ceremonies, festivals, Fairs, exhibits and displays, receptions and parties, athletic events, luncheons, outreach events, games, concerts and performances, races and walks, camp activities, and campus events.",
        microwave: "N/A",
        buzzcard: "N/A",
        vending: "N/A",
        imgurl: "https://tinyurl.com/2nzphmxj",
    },
    {
        key: 3,
        id: "crc",
        title: "Campus Recreation Center",
        desc: "This is the CRC! You can play sports like basketball, volleyball, soccer, badminton, fencing, or just exercise. You can also rent sports equipment here.",
        microwave: "N/A",
        buzzcard: "Requires buzzcard to enter the gym",
        vending: "Has a vending machine on the first floor near the cafe",
        imgurl: "https://tinyurl.com/2s4yjpvt",
    }, 
    {
        key: 4,
        id: "klaus",
        title: "Klaus Advanced Computing Building",
        desc: "The building is home to the College of Computing's School of Computer Science and its School of Computational Science and Engineering, three research centers (GTISC, CERCS and ARC), and over 20 College of Computing Research Labs. It also houses much of the School of Electrical Engineering's computer engineering faculty and support staff. The binary bridge links this building to the College of Computing Building.",
        microwave: "This building has two microwaves. One in the breakroom on the second and third floors near the giant stairs",
        buzzcard: "Requires buzzcard access after 6pm",
        vending: "Has a vending machine on the first floor",
        imgurl: "https://tinyurl.com/yfyba9xx",
    },
    {
        key: 5,
        id: "gilbert",
        title: "Price Gilbert Memorial Library",
        desc: "This is the main library of Georgia Tech. This is connected to Crosland Tower and the Clough Undergraduate Learning Commons, and is the main studying space for students.",
        microwave: "N/A",
        buzzcard: "Requires buzzcard access after 6pm",
        vending: "N/A",
        imgurl: "https://tinyurl.com/3tadushm",
    },
    {
        key: 6,
        id: "crosland",
        title: "Crosland Tower",
        desc: "This is part of the Georgia Tech's main library. It is connected to Price Gilbert and contains quiet study area unlike Gilbert library.",
        microwave: "N/A",
        buzzcard: "Requires buzzcard access after 6pm",
        vending: "Has a vending machine on the second, third and sixth floor",
        imgurl: "https://tinyurl.com/yx25nn8f",
    },

    {
      key: 7,
      id: "studentcenter",
      title: "Georgia Tech Student Center",
      desc: "This building houses 11 dining concepts, including some returning favorites and new options. The third floor of the building houses several new spaces for student programming, such as the Reflection Space, Grad Student Lounge, and Multicultural Lounge. Additionally, the building boasts several meeting spaces and two theaters that support student events, admissions tours, and more.",
      microwave: "N/A",
      buzzcard: "Closed after 11pm",
      vending: "N/A",
      imgurl: "https://i.imgur.com/iwDNOjg.jpg",
    },

    {
      key: 8,
      id: "stamps",
      title: "Stamps Health Services",
      desc: " This building provides multi-dimensional health care both to individuals and the Georgia Tech community. You can make an appoinment and submit immunizations forms on their website. They also have vaccine and flu shot clinics.",
      microwave: "N/A",
      buzzcard: "Does not require buzzcard access and is open from 8am - 5pm on the weekdays",
      vending: "N/A",
      imgurl: "https://tinyurl.com/4r3zkfx9",
    },


    {
      key: 9,
      id: "skiles",
      title: "Skiles Classroom Building",
      desc: "The School of Mathematics is located on the first and second floor of this building. The LMC Office is located in Skiles 336. Most faculty, staff, and undergraduate advisor offices are also located at Skiles. This building is kinda spooky.",
      microwave: "N/A",
      buzzcard: "Does not require buzzcard access but is locked after 8pm",
      vending: "not sure...",
      imgurl: "https://tinyurl.com/yc54ct6d",

   },

   {
    key: 10,
    id: "vanleer",
    title: "Van Leer Building",
    desc: "ECE administrative offices, classrooms, instructional and research labs (VIPs), and offices are located here. It is connected to the Interdisciplinary Design Commons which is a 15,000-square-foot, state-of-the-art makerspace—the largest of its kind in the nation—that caters specifically to electronics and computer engineering design and innovation. However, students of all majors can use the IDC, which like other makerspaces on campus offers them a hands-on learning environment.",
    microwave: "This building has a microwave on the fifth floor but is intended for emag research",
    buzzcard: "Requires buzzcard access after 6pm",
    vending: "N/A",
    imgurl: "https://tinyurl.com/y5xjbev6",
  },

  {
    key: 11,
    id: "howey",
    title: "Howey Physics Building",
    desc: "This building is comprised of 26,000 sq. ft. of instructional space (classrooms and laboratories), 156,000 sq. ft. of research laboratory space, and office space for faculty, post-doctoral fellows, graduate students and visitors. The School currently has 44 faculty members, over 225 undergraduate students, and 130 graduate students.",
    microwave: "N/A",
    buzzcard: "Closes after 8pm",
    vending: "N/A",
    imgurl: "https://tinyurl.com/msbfw2pd",
  },

  {
    key: 12,
    id: "willage",
    title: "West Village",
    desc: "West Village hosts the dining commons and pulsing music annex, all with lush outdoor green spaces. With an emphasis on sustainability and community, West Village is the place where students, faculty, and staff. The Dining Commons offers a fresh, food-forward approach in a community-centered area similar to a food hall. There are five micro-restaurants with innovative cuisine ranging from the rich Italian food in Olive to the vast flavors of the world at Spice Trail.",
    microwave: "N/A",
    buzzcard: "Requires buzzcard access and is open from 7am - 7pm on the weekend and 9am - 7pm on the weekend",
    vending: "On the ground floor",
    imgurl: "https://tinyurl.com/5n8w24bx",
  },
  {
    key: 13,
    id: "brittain",
    title: "Brittain Dining Hall",
    desc: "Brittain Dining Hall is one of three dining halls at Georgia Tech. It is located on east part of campus and known for its Gothic architecture which is rare at GT. But they have the least food options out of all dining halls.",
    microwave: "N/A",
    buzzcard: "Requires buzzcard access at all times. Building opens from 7:00AM to 10PM on weekdays only.",
    vending: "N/A",
    imgurl: "https://tinyurl.com/2p8a4c72",
  },
  {
    key: 14,
    id: "nav",
    title: "North Ave Dining Hall",
    desc: "North Ave Dining Hall, a.k.a. Nav, is located on the easternmost part of campus. It is not really spacious, so on weekends and nights, seats are mostly taken.",
    microwave: "N/A",
    buzzcard: "Requires buzzcard access at all times. Building opens from 7:00AM to 10:PM on weekdays and 9:00AM to 9:00PM during weekends.",
    vending: "N/A",
    imgurl: "https://tinyurl.com/3x7pu8bs",
  }

];

export default buildingInfo;
